### PR TITLE
Telemetry support using Sentry

### LINKED ISSUE #100: Measure and log crashes/unhandled errors
We've received quite a few reports of the extension crashing and/or not functioning correctly.

To help assess the impact, prioritize fixes, and track improvement we should capture all errors via some tooling (likely Sentry or similar) and be able to analyze the data to get how many crashes/unexpected errors current users are facing.

### PR DESCRIPTION
**Pull request by DylanTinianov**
Closes #100 

## Description

Added telemetry support to track errors using Sentry. Users can also enable/ disable this option in settings.

It seems there's no way to do actual crash reporting for vscode extensions (you can't add something to catch all unhandled exceptions; see https://github.com/Microsoft/vscode/issues/45264). The best we can do is internal exception handling and capture any of these exceptions with Sentry.

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: extension/src/telemetry.ts [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+  async deactivate (): Promise<void> {
+    await this.#sentryClose()
+    Telemetry.#activated = false
+  }
+
+  #sentryInit (): void {
+    if (!Telemetry.#activated) return
+    Sentry.init({
+      // vscode-cadence
+      dsn: 'https://4d98c4d4ac7e4892850f8e3d2e61c733@o114654.ingest.sentry.io/6568410',
```
Comment (psiemens) [inline extension/src/telemetry.ts:23]: I'd define this as a constant (maybe just at the top of this file) or a build variable so that it doesn't get lost as a magic string.

File: extension/src/telemetry.ts [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+  async #sentryClose (): Promise<void> {
+    if (!Telemetry.#activated) return
+    void await Sentry.close()
+  }
+
+  static captureException (exception: any, captureContent?: Type.CaptureContext | undefined): void {
+    if (!Telemetry.#activated) return
+    const transaction = Sentry.startTransaction({
+      op: 'Extension',
+      name: 'Transaction'
```
Comment (psiemens) [inline extension/src/telemetry.ts:38]: Are these values significant? Just wondering if they should be something more unique, but I don't know much about Sentry TBH.

File: package.json [hunk 3]
```diff
@@ -76,13 +76,13 @@
 				"cadence.flowCommand": {
 					"type": "string",
 					"default": "flow",
-					"description": "The command to invoke the Flow CLI",
+					"description": "The command to invoke the Flow CLI.",
```
Comment (psiemens) [inline package.json:79]: Bless your attention to detail 🙏

File: extension/src/main.ts [hunk 4]
```diff
@@ -1,17 +1,35 @@
...
+  // Initialize Sentry error handling
+  telemetry = new Telemetry(settings.activateTelemetry)
+
   // Initialize the extension
-  ext = Extension.initialize(ctx)
+  try {
+    ext = Extension.initialize(ctx)
+  } catch (e) {
+    Telemetry.captureException(e)
+  }
```
Comment (psiemens) [inline extension/src/main.ts:25]: It's a bit confusing that the telemetry object is accessed through both static methods (`Telemetry.captureException`) and instance methods (`telemetry.deactivate`). Can it just be a singleton?

File: extension/src/commands/command-controller.ts [hunk 5]
```diff
@@ -15,16 +16,20 @@ export class CommandController {
...
-    this.cmds.push(cmd)
+      this.cmds.push(cmd)
 
-    // ext.ctx.subscriptions.push(cmd)
-    // DEBUG_LOG('Registered command ' + command)
+      // ext.ctx.subscriptions.push(cmd)
+      // DEBUG_LOG('Registered command ' + command)
+    } catch (err) {
+      Telemetry.captureException(err)
+    }
```
Comment (psiemens) [inline extension/src/commands/command-controller.ts:32]: This silences the error for the user, which could be confusing. Maybe `throw` here?

File: extension/src/commands/command-controller.ts [hunk 6]
```diff
@@ -38,22 +43,47 @@ export class CommandController {
   }
 
   #restartServer (): void {
-    ext.emulatorCtrl.restartServer()
+    try {
+      ext.emulatorCtrl.restartServer()
+    } catch (err) {
+      Telemetry.captureException(err)
+      throw err
+    }
```
Comment (psiemens) [inline extension/src/commands/command-controller.ts:51]: I think a lot of these try/catch block are redundant because e.g. `restartServer` already contains a try/catch that doesn't not propagate the error up the stack.

File: extension/src/emulator/emulator-controller.ts [hunk 7]
```diff
@@ -70,25 +72,30 @@ export class EmulatorController {
...
+      ext.emulatorStateChanged()
+      await this.api.client.stop()
 
-    // Reset the language server
-    this.api.reset()
+      // Reset the language server
+      this.api.reset()
+    } catch (err) {
+      Telemetry.captureException(err)
+    }
```
Comment (psiemens) [inline extension/src/emulator/emulator-controller.ts:98]: Here's an example of an error that's being silenced. For one, this makes the try/catch block in `CommandController.stopEmulator` redundant, but it prevents the error from being reported to the user, who probably wants to know that something went wrong.

**Review by psiemens — COMMENTED** [review]
Thanks for tackling this one!

First off, just want to check that you saw the [extension telemetry documentation](https://code.visualstudio.com/api/extension-guides/telemetry) from the VS Code team. It has some good points.

Looking through this, I wonder if we can reduce the number of calls to `Telemetry.captureException`. As I mentioned in my code comments, there are a few redundant captures, and I'm worried that we'll accidentally add more of those as the codebase grows.

Despite not having a global exception handler, I wonder if there's still a way to cut down the number of calls to `captureException`. Maybe we could identify the "entry points" to the extension (i.e. commands, actions, events, etc that trigger code execution) and capture exceptions in those places. 

A few ideas:

- Wrap commands in a telemetry helper:

  ```js
  commands.registerCommand(command, withTelemetry(callback))
  ```
  
- Intercept all calls to the language server made with `this.client.sendRequest`

**Comment by DylanTinianov** [comment]
> 

Thanks for the great ideas. Turns out we only need to wrap the initialization of extension and commands with telemetry, since everything else occurs when a command is called anyways. We also don't need an instance of telemetry at all, so I moved it out of a class.

File: package.json [hunk 8]
```diff
@@ -113,6 +113,12 @@
 					],
 					"default": "off",
 					"description": "Traces the communication between VS Code and the Cadence language server."
+				},
+				"cadence.activateTelemetry": {
+					"type": "boolean",
+					"default": "true",
+					"description": "Allow Cadence to report errors to the developers.",
+					"scope": "resource"
 				}
```
Comment (psiemens) [inline package.json:122]: I don't think we should have our own telemetry toggle. The VS Code documentation encourages extensions to respect the global VS Code `isTelemetryEnabled` flag so that users have a central place to enabled/disable telemetry (ref: https://code.visualstudio.com/api/extension-guides/telemetry#without-the-telemetry-module).

Furthermore, even if we do use a custom setting, we still need to respect the global setting:

> Adding a custom telemetry setting is not an exemption from respecting a user's decision and the isTelemetryEnabled and onDidChangeTelemetryEnabled flag must always be respected. If isTelemetryEnabled reports false, even if your setting is enabled, telemetry must not be sent.


Lastly, I don't think we should enable it by default; developers expect telemetry to be an opt-in feature. Using the global setting gets us that quality as well.

Comment (DylanTinianov) [reply package.json:122]: Already updated this! The initialization function in telemetry is ensuring isTelemetryEnabled is also true. I will set the default for our flag to false.

File: CODEOWNERS [hunk 9]
```diff
@@ -1 +1 @@
-@10thfloor @turbolent @psiemens
\ No newline at end of file
+@10thfloor @turbolent @psiemens @DylanTinianov
```
Comment (psiemens) [inline CODEOWNERS:1]: Sneaky! JK, welcome to the team.

File: package.json (hunk 8 above)
Comment (psiemens) [reply package.json]: Oh great! I missed that.

But I'd argue that we don't need to have the `activateTelemetry` toggle at all. The VS Code docs seem to recommend just using the global `isTelemetryEnabled` to enable/disable telemetry in an extension. Do you think we need our own setting?

I guess I just doubt that users will toggle two settings to enable our telemetry.

**Review by psiemens — COMMENTED** [review]
Sorry, one last comment!

File: package.json (hunk 8 above)
Comment (DylanTinianov) [reply package.json]: Okay I see what you're saying, I agree that we don't need our own setting.

**Review by psiemens — APPROVED** [review]
🚢
