### PR TITLE
Emulator location detection

### LINKED ISSUE #244: Detect wrong emulator startup place
When running an emulator if not started in the project folder, the VSCode won't work using the codelenses as it expects different keys. The error looks like this:
```
execution error code 1009: [Error Code: 1009] error caused by: 1 error occurred:
	* transaction verification failed: [Error Code: 1006] invalid proposal key: public key 0 on account f8d6e0586b0a20c7 does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account f8d6e0586b0a20c7 does not have a valid signature: signature is not valid
```

We could handle this error on the client and suggest to the user they should check whether they are running the emulator in the right place.

### PR DESCRIPTION
**Pull request by DylanTinianov**
Closes #244 

## Description
The extension will now only connect to an emulator if it's running with the corresponding public to the private key in flow.json config.

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

File: extension/src/emulator/local/emulatorScanner.ts [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+const ECDSA_P256 = ec('p256')
+
+interface EmulatorConfig {
+  service_key: string
+}
+
+let showLocationWarning = true
+
+export async function verifyEmulator (): Promise<boolean> {
+  const flowJsonPath = await Config.getConfigPath()
```
Comment (sideninja) [inline extension/src/emulator/local/emulatorScanner.ts:20]: Shouldn't Config module rather have a method that is `Config.load()` or something like that, it feels that module is meant to handle loading of config and it will be reusable from that place in future.

File: extension/src/emulator/local/emulatorScanner.ts [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+  const flowJsonData = JSON.parse(fs.readFileSync(flowJsonPath, 'utf-8'))
+
+  let flowJsonPrivKey: string
+  try {
+    flowJsonPrivKey = flowJsonData.accounts['emulator-account'].key
+  } catch (err) {
+    console.log(`Could not read emulator-account key from ${flowJsonPath}`)
+    return false
+  }
```
Comment (sideninja) [inline extension/src/emulator/local/emulatorScanner.ts:29]: I feel all this should be part of the Config module. It clearly has to do only with config, and I would advise making a method on that module that returns a loaded flow.json object (which might be useful in future from other parts) and then also have a method t get the emulator account object.

File: extension/src/emulator/local/emulatorScanner.ts [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+
+  let emulatorPublicKey: string
+  try {
+    const response = await fetch(emulatorConfigURL)
+    const config: EmulatorConfig = JSON.parse(await response.text())
+    emulatorPublicKey = config.service_key.substring(2)
```
Comment (sideninja) [inline extension/src/emulator/local/emulatorScanner.ts:35]: If this is mean to remove `0x` you rather do replace('0x') it will be safer.

File: extension/src/emulator/local/emulatorScanner.ts [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+
+  // Verify flow.json public key matches emulator public key
+  const key = ECDSA_P256.keyFromPrivate(flowJsonPrivKey)
+  const flowJsonPublicKey = key.getPublic('hex').toString().substring(2)
+
+  if (emulatorPublicKey !== flowJsonPublicKey) {
+    if (showLocationWarning) {
+      void window.showWarningMessage(`Emulator detected running with different keys than your flow.json 
+      config. To connect an emulator, please run 'flow emulator' in the same directory as your flow.json`)
+      showLocationWarning = false // Avoid spamming the location warning
```
Comment (sideninja) [inline extension/src/emulator/local/emulatorScanner.ts:50]: You can ignore this for now, but just for future reference something to think about in terms of good code architecture is that you try to separate your domain logic with UI handling, so in this case this function gets "dirty" with UI stuff, which has a lot of downsides, like harder to test, a lot of different places where UI is handled etc. You should always try combine the UI handling in a single module, like you started with the emulator controller. Again I don't want you to stress about this now and change it, but just a tip.

**Review by sideninja — COMMENTED** [review]
Left some minor comments.

File: extension/src/emulator/local/emulatorScanner.ts (hunk 3 above)
Comment (DylanTinianov) [reply extension/src/emulator/local/emulatorScanner.ts:35]: Updated

File: extension/src/emulator/local/emulatorScanner.ts (hunk 4 above)
Comment (DylanTinianov) [reply extension/src/emulator/local/emulatorScanner.ts:50]: Yeah sounds good. I did create a UI controller for all the components and separate that, but with popups it becomes more messy.

File: extension/src/emulator/local/emulatorScanner.ts (hunk 2 above)
Comment (DylanTinianov) [reply extension/src/emulator/local/emulatorScanner.ts]: Yeah good idea!

**Review by sideninja — APPROVED** [review]
