### PR TITLE
General Dependency Installer and installers for Flow CLI

### LINKED ISSUE #11: Enhancement: Install flow-cli (runtime dependencies) if not found
### Issue To Be Solved

When the extension is published on the public Marketplace, users could download and install it without having first installed the flow-cli. The extension does not work without the cli already installed on a user's system.

### Possible Solution

Add "runtimeDependencies" to the extension config, and code for detecting and installing the flow-cli, if not detected. 
Similar to:
https://blog.lextudio.com/how-to-acquire-dependencies-for-visual-studio-code-extensions-9ca828cb168d

### LINKED ISSUE #125: Create a Dependency Installer to manage runtime dependencies
## Instructions

Create a Dependency Installer to manage runtime dependencies

vscode-candence + dependency installer

### PR DESCRIPTION
**Pull request by DylanTinianov**
Closes #11 
Closes #125 

## Description

Created a dependency installer for managing runtime dependencies
- Registers a list of installers to verify if dependencies are installed
- Prompts user to install missing dependencies 
- Extendable to add more dependencies in the future.

Created an abstract Installer class for new runtime installers.

Added a runtime installer for Flow CLI:
- Installs Flow CLI on various systems
- Enable users to install Homebrew through a terminal to then install flow-cli on mac / linux

Added a command to vscode for users to check dependencies
______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: extension/src/dependency-installer/dependency-installer.ts [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+  }
+
+  #allInstalled (): boolean {
+    let installed: boolean = true
+    this.registeredInstallers.forEach((installer) => {
+      if (!installer.isInstalled()) {
+        installed = false
+      }
+    })
+    return installed
```
Comment (sideninja) [inline extension/src/dependency-installer/dependency-installer.ts:70]: NIT: you can simplify the code. (not tested)
```suggestion
    return this.registeredInstallers.find(installer => !installer.isInstalled())
```

File: extension/src/utils/utils.ts [hunk 2]
```diff
@@ -6,6 +7,28 @@ import {
 
 export const FILE_PATH_EMPTY = ''
 
+export function promptUserInfoMessage (message: string, buttonText: string, callback: Function): void {
```
Comment (sideninja) [inline extension/src/utils/utils.ts:10]: Do you think you could move prompts as part of the UI module? When I use utils I always have first think if this makes sense to be a part of something else. It often is the case. I feel like utils is like that one close in the house you have a bunch of random stuff in, but usually it makes sense to group that in other places.

**Review by sideninja — APPROVED** [review]
Really nice! 🔥 Well architectured. I left some minor comments but LGTM.
